import esbuild from "esbuild";
import process from "process";
import { copyFileSync } from "fs";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const pluginDir = process.env.OBSIDIAN_PLUGIN_DIR || ".";

const copyAssets = () => {
	copyFileSync("manifest.json", `${pluginDir}/manifest.json`);
	copyFileSync("styles.css", `${pluginDir}/styles.css`);
};

const copyPlugin = {
	name: "copy-plugin",
	setup(build) {
		build.onEnd(() => {
			copyAssets();
			console.log("Copied manifest.json and styles.css to plugin dir");
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${pluginDir}/main.js`,
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
